### ISSUE TITLE
страница ввода гостей, возраст

### ISSUE THREAD

**Issue by Zalexx08** [o-bender/raduga_line#20]
При указании возраста стоимость не пересчитывается

![default](https://user-images.githubusercontent.com/38527203/41407233-7693c7ac-6fd7-11e8-8c2f-5a70f76f58cf.png)

**Comment by o-bender** [comment]
Какие: номер, тариф, возраст?

**Comment by Zalexx08** [comment]
"Стандарт одноместный", "без лечения", от 2 до 5 лет
