### ISSUE TITLE
Страница ввода данных туристов, стоимость

### ISSUE THREAD

**Issue by Zalexx08** [o-bender/raduga_line#54]
Категория "Двухместный стандарт", тариф "Акция 10%". Если выбрать один номер и одно доп. место, то стоимость рассчитывается верно. Но на следующей странице стоимость уже другая.

![default](https://user-images.githubusercontent.com/38527203/42503542-9c53e610-8441-11e8-848e-16b6486ebd8d.png)

![default](https://user-images.githubusercontent.com/38527203/42503672-f2a00b16-8441-11e8-9a0d-455a4f4a64f8.png)

**Comment by o-bender** [comment]
Уверен? Перепроверь.

**Comment by Zalexx08** [comment]
Перепроверил. Надо выбирать именно номер на одного. Доп. место можно не выбирать.
