### ISSUE TITLE
Обнуляется информация о заказе 

### ISSUE THREAD

**Issue by Svetlana12** [o-bender/raduga_line#75]
У категории нет доп мест и продажа номерами. 
Если на сайте выбрать номер данной категории, то на странице "Оплата заказа" в блоке "Информация о заказе" проставляются нулевые значения, а в блоке "Информация о гостях" нет данных.
![image](https://user-images.githubusercontent.com/38527199/44515381-17a41000-a6cb-11e8-93c6-fad1c5de8f1e.png)

**Comment by o-bender** [comment]
Как мне найти такую категорию? Напиши пожалуйста ID санатория, название категории и даты.
