### ISSUE TITLE
Странный плательщик

### ISSUE THREAD

**Issue by Zalexx08** [o-bender/raduga_line#77]
В Firefox заметил, что если несколько часов не открывать страницу с модулем бронирования, а потом попытаться оформить заказ, то на странице для ввода данных туристов в поле "Покупатель" вместо названия организации подставляется какой то символ. Если его так и оставить, то заказ проходит, в Портье появляются путевки, у которых в качестве плательщика указан символ, что то типа креста, а в письмах, подтверждающих бронирование, а также в счете и в ваучере покупатель не указан.

![default](https://user-images.githubusercontent.com/38527203/44852945-4000b100-ac6d-11e8-9508-bdd0758724c9.png)

 
 
![default](https://user-images.githubusercontent.com/38527203/44853150-d634d700-ac6d-11e8-96e7-8ab7b57fb7fe.png)

**Comment by o-bender** [comment]
Несколько часов?))))
Опиши подробней, свои действия. Что значит "не открывать страницу"? На каком этапе бронирования ты остановился перед тем как продолжил?

**Comment by Zalexx08** [comment]
Ну да. Компьютер на ночь не выключаю, с утра открываю браузер, захожу на страницу модуля бронирования, а там вместо "Алеан" подставляется этом символ. На каком этапе перед этим остановился не могу сказать. Завтра проверю.

**Comment by Zalexx08** [comment]
Сегодня повторилось. Вчера закрыл браузер когда модуль бронирования был открыт на странице с выбором категорий. Сегодня открылась изначально страница с выбором дат приезда и отъезда. После выбора количества путевок на следующей странице в поле "Покупатель" снова этот символ подставился.

**Comment by o-bender** [comment]
Попробуй очистить кеш.

**Comment by Zalexx08** [comment]
кеш очистил, в понедельник проверю

**Comment by Zalexx08** [comment]
сегодня снова повторилось в Firefox. В Google Chrome такого не замечал.

**Comment by Zalexx08** [comment]
сегодня подставился вот такой набор символов

![default](https://user-images.githubusercontent.com/38527203/45280914-df7c3a00-b4de-11e8-8cde-6427f77d4bb0.png)

**Comment by o-bender** [comment]
Не получается у меня это воспроизвести :)
Надо это увидеть.

**Comment by Zalexx08** [comment]
Как я понял, такое случается только с русскими названиями организаций.
