### ISSUE TITLE
Нет доп. мест

### ISSUE THREAD

**Issue by Zalexx08** [o-bender/raduga_line#80]
В браузере Google Chrome. После того как выберешь количество путевок на основных местах нет возможности указать количество доп. мест. 
Если нажать на "Забронировать", то выдается сообщение "Данные устарели. Необходимо произвести повторный поиск номеров."

![default](https://user-images.githubusercontent.com/38527203/44913470-25463f00-ad36-11e8-9783-b7659c23b4e6.png)

**Comment by o-bender** [comment]
Ctrl+F5 пробовал? очищал кеш?

**Comment by Zalexx08** [comment]
после очистки кеша доп. места появились
