### ISSUE TITLE
кол-во дней

### ISSUE THREAD

**Issue by Svetlana12** [o-bender/raduga_line#94]
В строке "тариф доступен для бронирования при продолжительности путёвки от __ дней" менять дней/суток/ночей в зависимости от значения, которое указано над ценой ("Стоимость за __ суток")

**Comment by o-bender** [comment]
Исправил, не забудь перезапустить нужный санаторий в админке.

**Comment by Svetlana12** [comment]
не меняется текст
![default](https://user-images.githubusercontent.com/38527199/48696223-59712380-ebf2-11e8-9330-240af71c67bc.png)
